title: nhs000
description: Technical blog
author: nhs000

# Google Analytics
google_analytics: G-WJWZBSMLY4

# Build settings
theme: minima
permalink: /:title/

# Minima theme settings
minima:
  skin: classic
  date_format: "%b %-d, %Y"

# Exclude from processing
exclude:
  - publish.sh
  - README.md
  - .gitignore
